### ISSUE TITLE
Persister doesn't initialize even after retry connection to auth

### ISSUE THREAD

**Issue by matheuscampanhaf** [dojot/history#29]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
A bug.

* **What is the current behavior?**
When auth isn't up yet, persister waits some time to retry the requisition to get tenants. 
But, sometimes, these waits and retries aren't enough and the service is not initializing.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Just bring up all the services.
Here is the log:
![issue_persister](https://user-images.githubusercontent.com/19478545/49646397-0971c980-fa06-11e8-9d27-edaa73db20c1.png)

* **What is the expected behavior?**
The expected behavior is to persister get the list of tenants from Auth.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: Battojutsu
  - Environment: docker-compose
  - Operating system: Ubuntu 16.04, Fedora 28

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by giovannicuriel** [comment]
The startup behavior is changed by dojot/dojot-module-python#10. With that PR, persister process is stopped after retrying a few times (it won't be in limbo anymore)

**Comment by matheuscampanhaf** [comment]
Nice!!
