### ISSUE TITLE
Problema para subir a API de history no Ambiente de desenvolvimento

### ISSUE THREAD

**Issue by Mesdra** [dojot/history#58]
Estou desenvolvendo um projeto com o dojot, e tenho que criar novos EndPoints para a API  de history da plataforma. Pelo que eu entendi a API necessita da biblioteca criada por vcs dojot-module-python  para funcionar corretamente, entretanto não consegui subir ele no meu ambiente, gostaria de saber quais são os passos que eu devo seguir para subir a api do dojot em um ambiente de desenvolvimento.

Versões que eu estou utilizando 

history = https://github.com/dojot/history/tree/release/1.1.0

dojot-module-python = https://github.com/dojot/dojot-module-python/tree/release/0.0.1

**Comment by mprevide** [comment]
Talvez seja mais simples você executar o history dentro no ambiente do  docker-compose, para tal: 

1. - fazer suas alterações no código do history
2. - gerando uma imagem docker do history
3. - alterando a tag do history no docker-compose
4. - reiniciando o container do history.

**Comment by Mesdra** [comment]
Eu tentei fazer o seguinte, eu subi o docker compose do dojot expondo a porta 8945 do container  de history, e dentro do container eu criei uma API simples em python retornando um hello word apontando para a porta 8945,  e consegui acessar normalmente ela da minha maquina, então eu editei o arquivo app.py trocando a porta do servidor de debug

if __name__ == '__main__':
    from wsgiref import simple_server  # NOQA
    httpd = simple_server.make_server('127.0.0.1', 8945, app)
    httpd.serve_forever()


então eu executei o server com python app.py, dentro do container eu consigo utilizara API que eu subi normalmente consultando os dados do dojot, só que mesmo assim eu não consigo acessar ela da minha maquina, quando eu bato no endpoint eu recebo o erro "curl: (56) Recv failure: Conexão fechada pela outra ponta" estou esquecendo de alguma coisa ?

culr que eu estou utilizando 

curl -H "Content-Type: application/json" -H "Authorization: Bearer  ${jwt}" -X GET "localhost:8945/device/606c00/history?lastN=200"


docker ps 

CONTAINER ID        IMAGE                                     COMMAND                  CREATED             STATUS                          PORTS                                             NAMES
850d17102717        dojot/history:v1.0.0                      "./docker/falcon-doc…"   4 minutes ago       Up 4 minutes                    8000/tcp, 0.0.0.0:8945->8945/tcp                  dojot_history_1

**Comment by mprevide** [comment]
> Eu tentei fazer o seguinte, eu subi o docker compose do dojot expondo a porta 8945 do container de history, e dentro do container eu criei uma API simples em python retornando um hello word apontando para a porta 8945, e consegui acessar normalmente ela da minha maquina, então eu editei o arquivo app.py trocando a porta do servidor de debug
> 
> `if __name__ == '__main__': from wsgiref import simple_server # NOQA httpd = simple_server.make_server('127.0.0.1', 8945, app) httpd.serve_forever()`
> 
> então eu executei o server com python app.py, dentro do container eu consigo utilizara API que eu subi normalmente consultando os dados do dojot, só que mesmo assim eu não consigo acessar ela da minha maquina, quando eu bato no endpoint eu recebo o erro "curl: (56) Recv failure: Conexão fechada pela outra ponta" estou esquecendo de alguma coisa ?
> 
> culr que eu estou utilizando
> 
> curl -H "Content-Type: application/json" -H "Authorization: Bearer ${jwt}" -X GET "localhost:8945/device/606c00/history?lastN=200"
> 
> docker ps
> 
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> 850d17102717 dojot/history:v1.0.0 "./docker/falcon-doc…" 4 minutes ago Up 4 minutes 8000/tcp, 0.0.0.0:8945->8945/tcp dojot_history_1

Para acessar de fora do ambiente do docker-compose você teria que utilizar o IP do container do history. Ou  para utilizar como localhost você teria que adicionar a rota no kong.conf.sh para a nova porta.

**Comment by mprevide** [comment]
> Eu tentei fazer o seguinte, eu subi o docker compose do dojot expondo a porta 8945 do container de history, e dentro do container eu criei uma API simples em python retornando um hello word apontando para a porta 8945, e consegui acessar normalmente ela da minha maquina, então eu editei o arquivo app.py trocando a porta do servidor de debug
> 
> `if __name__ == '__main__': from wsgiref import simple_server # NOQA httpd = simple_server.make_server('127.0.0.1', 8945, app) httpd.serve_forever()`
> 
> então eu executei o server com python app.py, dentro do container eu consigo utilizara API que eu subi normalmente consultando os dados do dojot, só que mesmo assim eu não consigo acessar ela da minha maquina, quando eu bato no endpoint eu recebo o erro "curl: (56) Recv failure: Conexão fechada pela outra ponta" estou esquecendo de alguma coisa ?
> 
> culr que eu estou utilizando
> 
> curl -H "Content-Type: application/json" -H "Authorization: Bearer ${jwt}" -X GET "localhost:8945/device/606c00/history?lastN=200"
> 
> docker ps
> 
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> 850d17102717 dojot/history:v1.0.0 "./docker/falcon-doc…" 4 minutes ago Up 4 minutes 8000/tcp, 0.0.0.0:8945->8945/tcp dojot_history_1

Por que você gostaria de alterar a porta do serviço?

**Comment by bizetti** [comment]
Ticket analysis meeting (April, 17th): Close.
